name: GitHub Actions CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Bước 1 - Tai code tu GitHub ve may ao
      uses: actions/checkout@v4

    - name: Bước 2 - Thiet lap moi truong Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Bước 3 - Cai dat cac thu vien (Dependencies)
      run: npm install

    - name: Bước 4 - Chay kiem tra code (Test)
      run: npm test
# Trigger
# Trigger
